export const COLORS = {
  white: 'white',
  purple: 'purple',
  black: 'black',
  lightgray: 'lightgray',
  orange: '#ff8000',
  green: 'green',
  blue: 'blue',
  red: 'red',
  yellow: 'yellow',
  skyblue: 'skyblue',
  gray: 'gray',
  pink: 'pink',
  deeppink: 'deeppink',
  hotpink: 'hotpink',
  navy: 'navy',
  midnightblue: 'midnightblue',
  darkblue: 'darkblue',
  darkslateblue: 'darkslateblue',
  indigo: 'indigo',
  aquamarine: 'aquamarine',
};
